---

- name: install supervisor
  apt: name=supervisor

- name: Create the Supervisor config file
  template: src=supervisor_config.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}.conf

- name: Re-read the Supervisor config files
  supervisorctl: name={{ application_name }} state=present

- name: Restart Supervisor
  supervisorctl: name={{ application_name }} state=restarted
